# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recv_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recv_msg.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0erecv_msg.proto\"K\n\trecv_info\x12\x12\n\nsession_id\x18\x01 \x02(\x0c\x12\x14\n\x0crequest_type\x18\x02 \x02(\x05\x12\x14\n\x0crequest_data\x18\x03 \x02(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RECV_INFO = _descriptor.Descriptor(
  name='recv_info',
  full_name='recv_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='recv_info.session_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_type', full_name='recv_info.request_type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_data', full_name='recv_info.request_data', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['recv_info'] = _RECV_INFO

recv_info = _reflection.GeneratedProtocolMessageType('recv_info', (_message.Message,), dict(
  DESCRIPTOR = _RECV_INFO,
  __module__ = 'recv_msg_pb2'
  # @@protoc_insertion_point(class_scope:recv_info)
  ))
_sym_db.RegisterMessage(recv_info)


# @@protoc_insertion_point(module_scope)
