# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: change_scene.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='change_scene.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12\x63hange_scene.proto\">\n\x10\x63hange_scene_req\x12\x16\n\x0eproto_id_10002\x18\x63 \x01(\x08\x12\x12\n\nscene_name\x18\x01 \x02(\t\"K\n\x10\x63hange_scene_rsp\x12\x16\n\x0eproto_id_20002\x18\x63 \x01(\x08\x12\x0b\n\x03ret\x18\x01 \x02(\r\x12\x12\n\nscene_name\x18\x02 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CHANGE_SCENE_REQ = _descriptor.Descriptor(
  name='change_scene_req',
  full_name='change_scene_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_id_10002', full_name='change_scene_req.proto_id_10002', index=0,
      number=99, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scene_name', full_name='change_scene_req.scene_name', index=1,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=84,
)


_CHANGE_SCENE_RSP = _descriptor.Descriptor(
  name='change_scene_rsp',
  full_name='change_scene_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_id_20002', full_name='change_scene_rsp.proto_id_20002', index=0,
      number=99, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='change_scene_rsp.ret', index=1,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scene_name', full_name='change_scene_rsp.scene_name', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['change_scene_req'] = _CHANGE_SCENE_REQ
DESCRIPTOR.message_types_by_name['change_scene_rsp'] = _CHANGE_SCENE_RSP

change_scene_req = _reflection.GeneratedProtocolMessageType('change_scene_req', (_message.Message,), dict(
  DESCRIPTOR = _CHANGE_SCENE_REQ,
  __module__ = 'change_scene_pb2'
  # @@protoc_insertion_point(class_scope:change_scene_req)
  ))
_sym_db.RegisterMessage(change_scene_req)

change_scene_rsp = _reflection.GeneratedProtocolMessageType('change_scene_rsp', (_message.Message,), dict(
  DESCRIPTOR = _CHANGE_SCENE_RSP,
  __module__ = 'change_scene_pb2'
  # @@protoc_insertion_point(class_scope:change_scene_rsp)
  ))
_sym_db.RegisterMessage(change_scene_rsp)


# @@protoc_insertion_point(module_scope)
