# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: create_room.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_info_pb2 as common__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='create_room.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x63reate_room.proto\x1a\x11\x63ommon_info.proto\"<\n\x0f\x63reate_room_req\x12\x11\n\tgame_type\x18\x01 \x02(\r\x12\x16\n\x03\x63\x66g\x18\x02 \x02(\x0b\x32\t.game_cfg\"g\n\x0f\x63reate_room_rsp\x12\x0b\n\x03ret\x18\x01 \x02(\r\x12\x11\n\tgame_type\x18\x02 \x02(\r\x12\x0f\n\x07room_id\x18\x03 \x01(\r\x12\x0b\n\x03pos\x18\x04 \x01(\r\x12\x16\n\x03\x63\x66g\x18\x05 \x01(\x0b\x32\t.game_cfg')
  ,
  dependencies=[common__info__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CREATE_ROOM_REQ = _descriptor.Descriptor(
  name='create_room_req',
  full_name='create_room_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_type', full_name='create_room_req.game_type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cfg', full_name='create_room_req.cfg', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=100,
)


_CREATE_ROOM_RSP = _descriptor.Descriptor(
  name='create_room_rsp',
  full_name='create_room_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='create_room_rsp.ret', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_type', full_name='create_room_rsp.game_type', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='create_room_rsp.room_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='create_room_rsp.pos', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cfg', full_name='create_room_rsp.cfg', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=205,
)

_CREATE_ROOM_REQ.fields_by_name['cfg'].message_type = common__info__pb2._GAME_CFG
_CREATE_ROOM_RSP.fields_by_name['cfg'].message_type = common__info__pb2._GAME_CFG
DESCRIPTOR.message_types_by_name['create_room_req'] = _CREATE_ROOM_REQ
DESCRIPTOR.message_types_by_name['create_room_rsp'] = _CREATE_ROOM_RSP

create_room_req = _reflection.GeneratedProtocolMessageType('create_room_req', (_message.Message,), dict(
  DESCRIPTOR = _CREATE_ROOM_REQ,
  __module__ = 'create_room_pb2'
  # @@protoc_insertion_point(class_scope:create_room_req)
  ))
_sym_db.RegisterMessage(create_room_req)

create_room_rsp = _reflection.GeneratedProtocolMessageType('create_room_rsp', (_message.Message,), dict(
  DESCRIPTOR = _CREATE_ROOM_RSP,
  __module__ = 'create_room_pb2'
  # @@protoc_insertion_point(class_scope:create_room_rsp)
  ))
_sym_db.RegisterMessage(create_room_rsp)


# @@protoc_insertion_point(module_scope)
