# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dismiss_room.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dismiss_room.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12\x64ismiss_room.proto\"X\n\x12room_dismiss_state\x12\x0b\n\x03pos\x18\x01 \x02(\r\x12\x13\n\x0bwechat_info\x18\x02 \x02(\x0c\x12 \n\x05state\x18\x03 \x02(\x0e\x32\x11.state_in_dismiss\"*\n\x10\x64ismiss_room_req\x12\x16\n\x0eproto_id_10071\x18\x63 \x01(\x08\"`\n\x10\x64ismiss_room_rsp\x12\x16\n\x0eproto_id_20071\x18\x63 \x01(\x08\x12\x0b\n\x03ret\x18\x01 \x02(\r\x12\'\n\nlist_state\x18\x02 \x03(\x0b\x32\x13.room_dismiss_state\"P\n\x14\x64ismiss_room_opt_req\x12\x16\n\x0eproto_id_10072\x18\x63 \x01(\x08\x12 \n\x05state\x18\x01 \x02(\x0e\x32\x11.state_in_dismiss\"d\n\x14\x64ismiss_room_opt_rsp\x12\x16\n\x0eproto_id_20072\x18\x63 \x01(\x08\x12\x0b\n\x03ret\x18\x01 \x02(\r\x12\'\n\nlist_state\x18\x02 \x03(\x0b\x32\x13.room_dismiss_state\"f\n\x16syn_dismiss_room_state\x12\x16\n\x0eproto_id_20272\x18\x63 \x01(\x08\x12\x0b\n\x03ret\x18\x01 \x02(\r\x12\'\n\nlist_state\x18\x02 \x03(\x0b\x32\x13.room_dismiss_state*H\n\x10state_in_dismiss\x12\t\n\x05\x61gree\x10\x01\x12\n\n\x06reject\x10\x02\x12\n\n\x06un_opt\x10\x03\x12\x11\n\rapply_dismiss\x10\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_STATE_IN_DISMISS = _descriptor.EnumDescriptor(
  name='state_in_dismiss',
  full_name='state_in_dismiss',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='agree', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='reject', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='un_opt', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='apply_dismiss', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=542,
  serialized_end=614,
)
_sym_db.RegisterEnumDescriptor(_STATE_IN_DISMISS)

state_in_dismiss = enum_type_wrapper.EnumTypeWrapper(_STATE_IN_DISMISS)
agree = 1
reject = 2
un_opt = 3
apply_dismiss = 4



_ROOM_DISMISS_STATE = _descriptor.Descriptor(
  name='room_dismiss_state',
  full_name='room_dismiss_state',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='room_dismiss_state.pos', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wechat_info', full_name='room_dismiss_state.wechat_info', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='room_dismiss_state.state', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=110,
)


_DISMISS_ROOM_REQ = _descriptor.Descriptor(
  name='dismiss_room_req',
  full_name='dismiss_room_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_id_10071', full_name='dismiss_room_req.proto_id_10071', index=0,
      number=99, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=154,
)


_DISMISS_ROOM_RSP = _descriptor.Descriptor(
  name='dismiss_room_rsp',
  full_name='dismiss_room_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_id_20071', full_name='dismiss_room_rsp.proto_id_20071', index=0,
      number=99, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='dismiss_room_rsp.ret', index=1,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list_state', full_name='dismiss_room_rsp.list_state', index=2,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=252,
)


_DISMISS_ROOM_OPT_REQ = _descriptor.Descriptor(
  name='dismiss_room_opt_req',
  full_name='dismiss_room_opt_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_id_10072', full_name='dismiss_room_opt_req.proto_id_10072', index=0,
      number=99, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='dismiss_room_opt_req.state', index=1,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=334,
)


_DISMISS_ROOM_OPT_RSP = _descriptor.Descriptor(
  name='dismiss_room_opt_rsp',
  full_name='dismiss_room_opt_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_id_20072', full_name='dismiss_room_opt_rsp.proto_id_20072', index=0,
      number=99, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='dismiss_room_opt_rsp.ret', index=1,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list_state', full_name='dismiss_room_opt_rsp.list_state', index=2,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=436,
)


_SYN_DISMISS_ROOM_STATE = _descriptor.Descriptor(
  name='syn_dismiss_room_state',
  full_name='syn_dismiss_room_state',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_id_20272', full_name='syn_dismiss_room_state.proto_id_20272', index=0,
      number=99, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='syn_dismiss_room_state.ret', index=1,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list_state', full_name='syn_dismiss_room_state.list_state', index=2,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=540,
)

_ROOM_DISMISS_STATE.fields_by_name['state'].enum_type = _STATE_IN_DISMISS
_DISMISS_ROOM_RSP.fields_by_name['list_state'].message_type = _ROOM_DISMISS_STATE
_DISMISS_ROOM_OPT_REQ.fields_by_name['state'].enum_type = _STATE_IN_DISMISS
_DISMISS_ROOM_OPT_RSP.fields_by_name['list_state'].message_type = _ROOM_DISMISS_STATE
_SYN_DISMISS_ROOM_STATE.fields_by_name['list_state'].message_type = _ROOM_DISMISS_STATE
DESCRIPTOR.message_types_by_name['room_dismiss_state'] = _ROOM_DISMISS_STATE
DESCRIPTOR.message_types_by_name['dismiss_room_req'] = _DISMISS_ROOM_REQ
DESCRIPTOR.message_types_by_name['dismiss_room_rsp'] = _DISMISS_ROOM_RSP
DESCRIPTOR.message_types_by_name['dismiss_room_opt_req'] = _DISMISS_ROOM_OPT_REQ
DESCRIPTOR.message_types_by_name['dismiss_room_opt_rsp'] = _DISMISS_ROOM_OPT_RSP
DESCRIPTOR.message_types_by_name['syn_dismiss_room_state'] = _SYN_DISMISS_ROOM_STATE
DESCRIPTOR.enum_types_by_name['state_in_dismiss'] = _STATE_IN_DISMISS

room_dismiss_state = _reflection.GeneratedProtocolMessageType('room_dismiss_state', (_message.Message,), dict(
  DESCRIPTOR = _ROOM_DISMISS_STATE,
  __module__ = 'dismiss_room_pb2'
  # @@protoc_insertion_point(class_scope:room_dismiss_state)
  ))
_sym_db.RegisterMessage(room_dismiss_state)

dismiss_room_req = _reflection.GeneratedProtocolMessageType('dismiss_room_req', (_message.Message,), dict(
  DESCRIPTOR = _DISMISS_ROOM_REQ,
  __module__ = 'dismiss_room_pb2'
  # @@protoc_insertion_point(class_scope:dismiss_room_req)
  ))
_sym_db.RegisterMessage(dismiss_room_req)

dismiss_room_rsp = _reflection.GeneratedProtocolMessageType('dismiss_room_rsp', (_message.Message,), dict(
  DESCRIPTOR = _DISMISS_ROOM_RSP,
  __module__ = 'dismiss_room_pb2'
  # @@protoc_insertion_point(class_scope:dismiss_room_rsp)
  ))
_sym_db.RegisterMessage(dismiss_room_rsp)

dismiss_room_opt_req = _reflection.GeneratedProtocolMessageType('dismiss_room_opt_req', (_message.Message,), dict(
  DESCRIPTOR = _DISMISS_ROOM_OPT_REQ,
  __module__ = 'dismiss_room_pb2'
  # @@protoc_insertion_point(class_scope:dismiss_room_opt_req)
  ))
_sym_db.RegisterMessage(dismiss_room_opt_req)

dismiss_room_opt_rsp = _reflection.GeneratedProtocolMessageType('dismiss_room_opt_rsp', (_message.Message,), dict(
  DESCRIPTOR = _DISMISS_ROOM_OPT_RSP,
  __module__ = 'dismiss_room_pb2'
  # @@protoc_insertion_point(class_scope:dismiss_room_opt_rsp)
  ))
_sym_db.RegisterMessage(dismiss_room_opt_rsp)

syn_dismiss_room_state = _reflection.GeneratedProtocolMessageType('syn_dismiss_room_state', (_message.Message,), dict(
  DESCRIPTOR = _SYN_DISMISS_ROOM_STATE,
  __module__ = 'dismiss_room_pb2'
  # @@protoc_insertion_point(class_scope:syn_dismiss_room_state)
  ))
_sym_db.RegisterMessage(syn_dismiss_room_state)


# @@protoc_insertion_point(module_scope)
