# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enter_room.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enter_room.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10\x65nter_room.proto\"9\n\x0e\x65nter_room_req\x12\x16\n\x0eproto_id_10011\x18\x63 \x01(\x08\x12\x0f\n\x07room_id\x18\x01 \x02(\r\"5\n\x0e\x65nter_room_rsp\x12\x16\n\x0eproto_id_20011\x18\x63 \x01(\x08\x12\x0b\n\x03ret\x18\x01 \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENTER_ROOM_REQ = _descriptor.Descriptor(
  name='enter_room_req',
  full_name='enter_room_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_id_10011', full_name='enter_room_req.proto_id_10011', index=0,
      number=99, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='enter_room_req.room_id', index=1,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=77,
)


_ENTER_ROOM_RSP = _descriptor.Descriptor(
  name='enter_room_rsp',
  full_name='enter_room_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_id_20011', full_name='enter_room_rsp.proto_id_20011', index=0,
      number=99, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='enter_room_rsp.ret', index=1,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['enter_room_req'] = _ENTER_ROOM_REQ
DESCRIPTOR.message_types_by_name['enter_room_rsp'] = _ENTER_ROOM_RSP

enter_room_req = _reflection.GeneratedProtocolMessageType('enter_room_req', (_message.Message,), dict(
  DESCRIPTOR = _ENTER_ROOM_REQ,
  __module__ = 'enter_room_pb2'
  # @@protoc_insertion_point(class_scope:enter_room_req)
  ))
_sym_db.RegisterMessage(enter_room_req)

enter_room_rsp = _reflection.GeneratedProtocolMessageType('enter_room_rsp', (_message.Message,), dict(
  DESCRIPTOR = _ENTER_ROOM_RSP,
  __module__ = 'enter_room_pb2'
  # @@protoc_insertion_point(class_scope:enter_room_rsp)
  ))
_sym_db.RegisterMessage(enter_room_rsp)


# @@protoc_insertion_point(module_scope)
