# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exit_room.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_info_pb2 as common__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='exit_room.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x65xit_room.proto\x1a\x11\x63ommon_info.proto\" \n\rexit_room_req\x12\x0f\n\x07room_id\x18\x01 \x02(\r\"\x1c\n\rexit_room_rsp\x12\x0b\n\x03ret\x18\x01 \x02(\r')
  ,
  dependencies=[common__info__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EXIT_ROOM_REQ = _descriptor.Descriptor(
  name='exit_room_req',
  full_name='exit_room_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room_id', full_name='exit_room_req.room_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=70,
)


_EXIT_ROOM_RSP = _descriptor.Descriptor(
  name='exit_room_rsp',
  full_name='exit_room_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='exit_room_rsp.ret', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['exit_room_req'] = _EXIT_ROOM_REQ
DESCRIPTOR.message_types_by_name['exit_room_rsp'] = _EXIT_ROOM_RSP

exit_room_req = _reflection.GeneratedProtocolMessageType('exit_room_req', (_message.Message,), dict(
  DESCRIPTOR = _EXIT_ROOM_REQ,
  __module__ = 'exit_room_pb2'
  # @@protoc_insertion_point(class_scope:exit_room_req)
  ))
_sym_db.RegisterMessage(exit_room_req)

exit_room_rsp = _reflection.GeneratedProtocolMessageType('exit_room_rsp', (_message.Message,), dict(
  DESCRIPTOR = _EXIT_ROOM_RSP,
  __module__ = 'exit_room_pb2'
  # @@protoc_insertion_point(class_scope:exit_room_rsp)
  ))
_sym_db.RegisterMessage(exit_room_rsp)


# @@protoc_insertion_point(module_scope)
