# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gm_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gm_config.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0fgm_config.proto\")\n\x0fload_config_req\x12\x16\n\x0eproto_id_10050\x18\x63 \x01(\x08\"H\n\x0fload_config_rsp\x12\x16\n\x0eproto_id_20050\x18\x63 \x01(\x08\x12\x0b\n\x03ret\x18\x01 \x02(\r\x12\x10\n\x08\x63onf_arr\x18\x02 \x03(\x0c\"K\n\x0eopt_config_req\x12\x16\n\x0eproto_id_10051\x18\x63 \x01(\x08\x12\x0e\n\x06is_add\x18\x01 \x02(\x08\x12\x11\n\tconf_data\x18\x02 \x02(\x0c\"G\n\x0eopt_config_rsp\x12\x16\n\x0eproto_id_20051\x18\x63 \x01(\x08\x12\x0b\n\x03ret\x18\x01 \x02(\r\x12\x10\n\x08\x63onf_arr\x18\x02 \x03(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOAD_CONFIG_REQ = _descriptor.Descriptor(
  name='load_config_req',
  full_name='load_config_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_id_10050', full_name='load_config_req.proto_id_10050', index=0,
      number=99, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=60,
)


_LOAD_CONFIG_RSP = _descriptor.Descriptor(
  name='load_config_rsp',
  full_name='load_config_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_id_20050', full_name='load_config_rsp.proto_id_20050', index=0,
      number=99, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='load_config_rsp.ret', index=1,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='conf_arr', full_name='load_config_rsp.conf_arr', index=2,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=134,
)


_OPT_CONFIG_REQ = _descriptor.Descriptor(
  name='opt_config_req',
  full_name='opt_config_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_id_10051', full_name='opt_config_req.proto_id_10051', index=0,
      number=99, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_add', full_name='opt_config_req.is_add', index=1,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='conf_data', full_name='opt_config_req.conf_data', index=2,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=211,
)


_OPT_CONFIG_RSP = _descriptor.Descriptor(
  name='opt_config_rsp',
  full_name='opt_config_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_id_20051', full_name='opt_config_rsp.proto_id_20051', index=0,
      number=99, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='opt_config_rsp.ret', index=1,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='conf_arr', full_name='opt_config_rsp.conf_arr', index=2,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=284,
)

DESCRIPTOR.message_types_by_name['load_config_req'] = _LOAD_CONFIG_REQ
DESCRIPTOR.message_types_by_name['load_config_rsp'] = _LOAD_CONFIG_RSP
DESCRIPTOR.message_types_by_name['opt_config_req'] = _OPT_CONFIG_REQ
DESCRIPTOR.message_types_by_name['opt_config_rsp'] = _OPT_CONFIG_RSP

load_config_req = _reflection.GeneratedProtocolMessageType('load_config_req', (_message.Message,), dict(
  DESCRIPTOR = _LOAD_CONFIG_REQ,
  __module__ = 'gm_config_pb2'
  # @@protoc_insertion_point(class_scope:load_config_req)
  ))
_sym_db.RegisterMessage(load_config_req)

load_config_rsp = _reflection.GeneratedProtocolMessageType('load_config_rsp', (_message.Message,), dict(
  DESCRIPTOR = _LOAD_CONFIG_RSP,
  __module__ = 'gm_config_pb2'
  # @@protoc_insertion_point(class_scope:load_config_rsp)
  ))
_sym_db.RegisterMessage(load_config_rsp)

opt_config_req = _reflection.GeneratedProtocolMessageType('opt_config_req', (_message.Message,), dict(
  DESCRIPTOR = _OPT_CONFIG_REQ,
  __module__ = 'gm_config_pb2'
  # @@protoc_insertion_point(class_scope:opt_config_req)
  ))
_sym_db.RegisterMessage(opt_config_req)

opt_config_rsp = _reflection.GeneratedProtocolMessageType('opt_config_rsp', (_message.Message,), dict(
  DESCRIPTOR = _OPT_CONFIG_RSP,
  __module__ = 'gm_config_pb2'
  # @@protoc_insertion_point(class_scope:opt_config_rsp)
  ))
_sym_db.RegisterMessage(opt_config_rsp)


# @@protoc_insertion_point(module_scope)
