# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='login.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0blogin.proto\"\x13\n\x11get_gate_info_req\"3\n\x11get_gate_info_rsp\x12\x0b\n\x03ret\x18\x01 \x02(\r\x12\x11\n\tgate_info\x18\x02 \x01(\x0c\"\x1e\n\tlogin_req\x12\x11\n\tauth_info\x18\x01 \x02(\x0c\"<\n\tlogin_rsp\x12\x0b\n\x03ret\x18\x01 \x02(\r\x12\x11\n\tplayer_id\x18\x02 \x01(\x04\x12\x0f\n\x07room_id\x18\x03 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GET_GATE_INFO_REQ = _descriptor.Descriptor(
  name='get_gate_info_req',
  full_name='get_gate_info_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=34,
)


_GET_GATE_INFO_RSP = _descriptor.Descriptor(
  name='get_gate_info_rsp',
  full_name='get_gate_info_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='get_gate_info_rsp.ret', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gate_info', full_name='get_gate_info_rsp.gate_info', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=87,
)


_LOGIN_REQ = _descriptor.Descriptor(
  name='login_req',
  full_name='login_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth_info', full_name='login_req.auth_info', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=119,
)


_LOGIN_RSP = _descriptor.Descriptor(
  name='login_rsp',
  full_name='login_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='login_rsp.ret', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='login_rsp.player_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='login_rsp.room_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['get_gate_info_req'] = _GET_GATE_INFO_REQ
DESCRIPTOR.message_types_by_name['get_gate_info_rsp'] = _GET_GATE_INFO_RSP
DESCRIPTOR.message_types_by_name['login_req'] = _LOGIN_REQ
DESCRIPTOR.message_types_by_name['login_rsp'] = _LOGIN_RSP

get_gate_info_req = _reflection.GeneratedProtocolMessageType('get_gate_info_req', (_message.Message,), dict(
  DESCRIPTOR = _GET_GATE_INFO_REQ,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:get_gate_info_req)
  ))
_sym_db.RegisterMessage(get_gate_info_req)

get_gate_info_rsp = _reflection.GeneratedProtocolMessageType('get_gate_info_rsp', (_message.Message,), dict(
  DESCRIPTOR = _GET_GATE_INFO_RSP,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:get_gate_info_rsp)
  ))
_sym_db.RegisterMessage(get_gate_info_rsp)

login_req = _reflection.GeneratedProtocolMessageType('login_req', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN_REQ,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:login_req)
  ))
_sym_db.RegisterMessage(login_req)

login_rsp = _reflection.GeneratedProtocolMessageType('login_rsp', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN_RSP,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:login_rsp)
  ))
_sym_db.RegisterMessage(login_rsp)


# @@protoc_insertion_point(module_scope)
