# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='login.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0blogin.proto\"9\n\tlogin_req\x12\x19\n\x04type\x18\x01 \x02(\x0e\x32\x0b.login_type\x12\x11\n\tauth_info\x18\x02 \x02(\x0c\"O\n\tlogin_rsp\x12\x0b\n\x03ret\x18\x01 \x02(\r\x12\x11\n\tplayer_id\x18\x02 \x01(\x04\x12\x0f\n\x07room_id\x18\x03 \x01(\r\x12\x11\n\tgate_info\x18\x04 \x01(\x0c**\n\nlogin_type\x12\x11\n\rget_gate_info\x10\x01\x12\t\n\x05login\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_LOGIN_TYPE = _descriptor.EnumDescriptor(
  name='login_type',
  full_name='login_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='get_gate_info', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='login', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=155,
  serialized_end=197,
)
_sym_db.RegisterEnumDescriptor(_LOGIN_TYPE)

login_type = enum_type_wrapper.EnumTypeWrapper(_LOGIN_TYPE)
get_gate_info = 1
login = 2



_LOGIN_REQ = _descriptor.Descriptor(
  name='login_req',
  full_name='login_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='login_req.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auth_info', full_name='login_req.auth_info', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=72,
)


_LOGIN_RSP = _descriptor.Descriptor(
  name='login_rsp',
  full_name='login_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='login_rsp.ret', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='login_rsp.player_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='login_rsp.room_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gate_info', full_name='login_rsp.gate_info', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=153,
)

_LOGIN_REQ.fields_by_name['type'].enum_type = _LOGIN_TYPE
DESCRIPTOR.message_types_by_name['login_req'] = _LOGIN_REQ
DESCRIPTOR.message_types_by_name['login_rsp'] = _LOGIN_RSP
DESCRIPTOR.enum_types_by_name['login_type'] = _LOGIN_TYPE

login_req = _reflection.GeneratedProtocolMessageType('login_req', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN_REQ,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:login_req)
  ))
_sym_db.RegisterMessage(login_req)

login_rsp = _reflection.GeneratedProtocolMessageType('login_rsp', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN_RSP,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:login_rsp)
  ))
_sym_db.RegisterMessage(login_rsp)


# @@protoc_insertion_point(module_scope)
