# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_info_pb2 as common__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='opt.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\topt.proto\x1a\x11\x63ommon_info.proto\"P\n\x07opt_req\x12\x1d\n\x08opt_type\x18\x01 \x02(\x0e\x32\x0b.event_type\x12\x10\n\x08opt_data\x18\x02 \x02(\r\x12\x14\n\x0copt_data_str\x18\x03 \x02(\x0c\"(\n\x07opt_rsp\x12\x0b\n\x03ret\x18\x01 \x02(\r\x12\x10\n\x08ret_data\x18\x02 \x02(\x0c')
  ,
  dependencies=[common__info__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_OPT_REQ = _descriptor.Descriptor(
  name='opt_req',
  full_name='opt_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='opt_type', full_name='opt_req.opt_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='opt_data', full_name='opt_req.opt_data', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='opt_data_str', full_name='opt_req.opt_data_str', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=112,
)


_OPT_RSP = _descriptor.Descriptor(
  name='opt_rsp',
  full_name='opt_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='opt_rsp.ret', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret_data', full_name='opt_rsp.ret_data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=154,
)

_OPT_REQ.fields_by_name['opt_type'].enum_type = common__info__pb2._EVENT_TYPE
DESCRIPTOR.message_types_by_name['opt_req'] = _OPT_REQ
DESCRIPTOR.message_types_by_name['opt_rsp'] = _OPT_RSP

opt_req = _reflection.GeneratedProtocolMessageType('opt_req', (_message.Message,), dict(
  DESCRIPTOR = _OPT_REQ,
  __module__ = 'opt_pb2'
  # @@protoc_insertion_point(class_scope:opt_req)
  ))
_sym_db.RegisterMessage(opt_req)

opt_rsp = _reflection.GeneratedProtocolMessageType('opt_rsp', (_message.Message,), dict(
  DESCRIPTOR = _OPT_RSP,
  __module__ = 'opt_pb2'
  # @@protoc_insertion_point(class_scope:opt_rsp)
  ))
_sym_db.RegisterMessage(opt_rsp)


# @@protoc_insertion_point(module_scope)
