# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='player_data.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x11player_data.proto\"d\n\x0fsyn_player_data\x12\x16\n\x0eproto_id_20052\x18\x63 \x01(\x08\x12\x11\n\tplayer_id\x18\x01 \x02(\x04\x12\x13\n\x0bwechat_info\x18\x02 \x02(\x0c\x12\x11\n\tdata_info\x18\x03 \x02(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SYN_PLAYER_DATA = _descriptor.Descriptor(
  name='syn_player_data',
  full_name='syn_player_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_id_20052', full_name='syn_player_data.proto_id_20052', index=0,
      number=99, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='syn_player_data.player_id', index=1,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wechat_info', full_name='syn_player_data.wechat_info', index=2,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_info', full_name='syn_player_data.data_info', index=3,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['syn_player_data'] = _SYN_PLAYER_DATA

syn_player_data = _reflection.GeneratedProtocolMessageType('syn_player_data', (_message.Message,), dict(
  DESCRIPTOR = _SYN_PLAYER_DATA,
  __module__ = 'player_data_pb2'
  # @@protoc_insertion_point(class_scope:syn_player_data)
  ))
_sym_db.RegisterMessage(syn_player_data)


# @@protoc_insertion_point(module_scope)
