# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syn_owner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='syn_owner.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0fsyn_owner.proto\"q\n\x0esyn_owner_info\x12\x0b\n\x03ret\x18\x01 \x02(\r\x12\x11\n\tplayer_id\x18\x02 \x02(\x04\x12\x13\n\x0bwechat_info\x18\x03 \x02(\x0c\x12\x12\n\nlist_money\x18\x04 \x03(\x0c\x12\x16\n\x0e\x63ur_in_room_id\x18\x05 \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SYN_OWNER_INFO = _descriptor.Descriptor(
  name='syn_owner_info',
  full_name='syn_owner_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='syn_owner_info.ret', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='syn_owner_info.player_id', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wechat_info', full_name='syn_owner_info.wechat_info', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list_money', full_name='syn_owner_info.list_money', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cur_in_room_id', full_name='syn_owner_info.cur_in_room_id', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['syn_owner_info'] = _SYN_OWNER_INFO

syn_owner_info = _reflection.GeneratedProtocolMessageType('syn_owner_info', (_message.Message,), dict(
  DESCRIPTOR = _SYN_OWNER_INFO,
  __module__ = 'syn_owner_pb2'
  # @@protoc_insertion_point(class_scope:syn_owner_info)
  ))
_sym_db.RegisterMessage(syn_owner_info)


# @@protoc_insertion_point(module_scope)
